In [1]:
import pandas as pd

import numpy as np

In [2]:
arrest_data = pd.read_csv("Arrest_Data_from_2010_to_Present.csv")

arrest_data.head()

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
0,191811472,05/03/2019,1700.0,18,Southeast,1802,23,F,B,NaN,NaN,M,653.22 PC,NaN,91ST,FIGUEROA,"(33.9543, -118.2827)"
1,5614161,04/29/2019,1040.0,8,West LA,842,41,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)"
2,5615197,04/30/2019,615.0,6,Hollywood,663,27,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)"
3,5615701,04/30/2019,1100.0,9,Van Nuys,901,2,F,H,NaN,NaN,D,300(B)WIC,NaN,RAYMER,SEPULVEDA BL,"(34.2149, -118.4674)"
4,5615929,04/30/2019,1550.0,20,Olympic,2049,41,M,W,4.0,Aggravated Assault,F,245(A)(2)PC,ADW W/FIREARM,8TH ST,VERMONT,"(34.0578, -118.2916)"

In [3]:
arrest_data.shape

(1310127, 17)

In [4]:
arrest_data.columns

Index(['Report ID', 'Arrest Date', 'Time', 'Area ID', 'Area Name',
       'Reporting District', 'Age', 'Sex Code', 'Descent Code',
       'Charge Group Code', 'Charge Group Description', 'Arrest Type Code',
       'Charge', 'Charge Description', 'Address', 'Cross Street', 'Location'],
      dtype='object')

In [5]:
arrest_data['Arrest Date'].min()

'01/01/2010'

In [6]:
from datetime import datetime

In [7]:
arrest_data['Arrest Date'] = pd.to_datetime(arrest_data['Arrest Date'])

In [8]:
start_date = '01/01/2018'
end_date = '12/31/2018'

In [9]:
mask = (arrest_data['Arrest Date'] > '01/01/2018') & (arrest_data['Arrest Date'] <= '12/31/2018')

In [10]:
mask.tail()

1310122    False
1310123    False
1310124    False
1310125    False
1310126    False
Name: Arrest Date, dtype: bool

In [11]:
booking2018_data = arrest_data.loc[mask]

In [12]:
booking2018_data.head(3)

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
156,5213460,2018-01-24,1930.0,6,Hollywood,668,29,M,H,10.0,Fraud/Embezzlement,F,530.5(A)PC,GET CREDIT/ETC OTHER'S ID,ST ANDREWS,FOUNTAIN,"(34.0949, -118.3109)"
157,5257944,2018-03-15,310.0,7,Wilshire,743,33,F,O,1.0,Homicide,F,191.5(B)PC,VEH MANSLAUGHTR/OPER VESSEL DUI & DUR FEL,OLYMPIC,MASSELIN,"(34.0574, -118.3547)"
158,5328813,2018-06-01,1800.0,3,Southwest,356,44,F,B,16.0,Narcotic Drug Laws,F,11379(A)HS,TRANSPORT/SELL CONTROLLED SUBSTANCE,1600 W 36TH PL,NaN,"(34.0219, -118.3061)"

In [13]:
booking2018_data['Report ID'].count()

104040

In [14]:
booking2018_data.tail(3)

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
1290588,5509344,2018-12-31,720.0,11,Northeast,1133,25,M,H,6.0,Larceny,M,490.2PC,PETTY THEFT,3100 GLENDALE BL,NaN,"(34.1119, -118.2529)"
1290595,5509947,2018-12-31,2320.0,4,Hollenbeck,408,23,M,H,16.0,Narcotic Drug Laws,F,11378HS,POSSESSION CONTROLLED SUBSTANCE FOR SALE,HUNTINGTON,ROSEMEAD,"(34.0872, -118.176)"
1290614,5509405,2018-12-31,1200.0,19,Mission,1921,28,F,H,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,15100 POLK ST,NaN,"(34.3009, -118.4696)"

In [15]:
small = ['Vehicle Theft','Robbery','Burglary', 'Receive Stolen Property']

small_data=booking2018_data[booking2018_data['Charge Group Description'].isin(small)]

small_data.shape

(8428, 17)

In [16]:
small_data.tail(3)

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
1290453,5509149,2018-12-30,2230.0,12,77th Street,1256,28,M,H,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,FLORENCE AV,BROADWAY ST,"(33.9747, -118.2783)"
1290486,5509524,2018-12-31,1300.0,11,Northeast,1128,21,M,B,3.0,Robbery,F,211PC,ROBBERY,YORK BL,FIGUEROA BL,"(34.1152, -118.1837)"
1290614,5509405,2018-12-31,1200.0,19,Mission,1921,28,F,H,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,15100 POLK ST,NaN,"(34.3009, -118.4696)"

In [17]:
small_data['Age'].sort_values

<bound method Series.sort_values of 167        43
172        32
173        26
175        32
176        27
177        20
178        25
184        18
185        38
193        27
194        21
197        39
198        26
2586       26
2590       20
2616       31
2624       38
2625       25
2627       34
2628       32
2658       38
4733       21
4735       24
4737       59
4761       18
4762       19
4769       37
6754       33
6760       31
6774       19
           ..
1289157    17
1289163    31
1289166    26
1289171    32
1289174    38
1289175    18
1289179    16
1289184    25
1289189    19
1289228    43
1289232    23
1289236    39
1289400    24
1289405    28
1289537    38
1289830    27
1289927    23
1289945    33
1289953    58
1290025    28
1290062    23
1290107    36
1290132    20
1290147    31
1290201    22
1290288    39
1290333    18
1290453    28
1290486    21
1290614    28
Name: Age, Length: 8428, dtype: int64>

In [18]:
np.quantile(small_data['Age'], .95)

52.0

In [19]:
mask10_18 = (arrest_data['Arrest Date'] >= '01/01/2010') & (arrest_data['Arrest Date'] <= '12/31/2018')

In [20]:
mask10_18.head(3)

0    False
1    False
2    False
Name: Arrest Date, dtype: bool

In [21]:
booking10_18_data = arrest_data.loc[mask10_18]

In [22]:
booking10_18_data.tail(3)

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
1310112,9919836,2010-01-19,800.0,3,Southwest,361,37,F,O,6.0,Larceny,F,487(A)PC,GRAND THEFT MONEY/PROPERTY > $400,3900 GIBRALTAR AV,NaN,"(34.0161, -118.3547)"
1310113,8526595,2013-10-15,1645.0,15,N Hollywood,1505,22,M,H,24.0,Miscellaneous Other Violations,F,594(B)(1)PC,VANDALISM W/LOSS VALUED EQ OR > $400,7400 CAMELLIA AV,NaN,"(34.2061, -118.3823)"
1310114,9791154,2010-01-19,2200.0,8,West LA,857,37,F,O,13.0,Prostitution/Allied,M,647(B)PC,PROSTITUTION,1200 S BEVERLY DR,NaN,"(34.0546, -118.3953)"

In [23]:
booking10_18_data.shape

(1231627, 17)

In [24]:
arrest_data['Arrest Type Code'].head()

0    M
1    F
2    F
3    D
4    F
Name: Arrest Type Code, dtype: object

In [25]:
start_date = '01/01/2010'
end_date = '12/31/2010'

In [26]:
mask_10 = (arrest_data['Arrest Date'] >= '01/01/2010') & (arrest_data['Arrest Date'] <= '12/31/2010')

In [27]:
mask_10.head(3)

0    False
1    False
2    False
Name: Arrest Date, dtype: bool

In [28]:
arrest_data_10 = arrest_data.loc[mask_10].head(3)

In [29]:
arrest_data_10.tail(10)

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
6722,2593624,2010-12-31,1915.0,7,Wilshire,776,41,M,B,24.0,Miscellaneous Other Violations,M,166(A)(4)PC,CONTEMPT OF COURT - DISOBEY COURT ORDER,4500 W WASHINGTON BL,NaN,"(34.0441, -118.3378)"
32877,2281627,2010-03-31,1730.0,15,N Hollywood,1525,37,M,W,6.0,Larceny,M,484(A)PC,GRAND THEFT (OVER $400),6100 LAUREL CANYON BL,NaN,"(34.1815, -118.3965)"
36970,2292485,2010-04-09,1700.0,19,Mission,1999,43,M,H,16.0,Narcotic Drug Laws,F,11350(A)HS,POSSESSION NARCOTIC CONTROLLED SUBSTANCE,WOODMAN,SATICOY,"(34.2095, -118.4309)"

In [30]:
arrest_data_10.head(100)

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
6722,2593624,2010-12-31,1915.0,7,Wilshire,776,41,M,B,24.0,Miscellaneous Other Violations,M,166(A)(4)PC,CONTEMPT OF COURT - DISOBEY COURT ORDER,4500 W WASHINGTON BL,NaN,"(34.0441, -118.3378)"
32877,2281627,2010-03-31,1730.0,15,N Hollywood,1525,37,M,W,6.0,Larceny,M,484(A)PC,GRAND THEFT (OVER $400),6100 LAUREL CANYON BL,NaN,"(34.1815, -118.3965)"
36970,2292485,2010-04-09,1700.0,19,Mission,1999,43,M,H,16.0,Narcotic Drug Laws,F,11350(A)HS,POSSESSION NARCOTIC CONTROLLED SUBSTANCE,WOODMAN,SATICOY,"(34.2095, -118.4309)"

In [31]:
import re
    
fel = arrest_data_10['Arrest Type Code'].str.contains('F')

felo_10 = arrest_data_10[fel]

felo_10

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
36970,2292485,2010-04-09,1700.0,19,Mission,1999,43,M,H,16.0,Narcotic Drug Laws,F,11350(A)HS,POSSESSION NARCOTIC CONTROLLED SUBSTANCE,WOODMAN,SATICOY,"(34.2095, -118.4309)"

In [32]:
felo_10

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
36970,2292485,2010-04-09,1700.0,19,Mission,1999,43,M,H,16.0,Narcotic Drug Laws,F,11350(A)HS,POSSESSION NARCOTIC CONTROLLED SUBSTANCE,WOODMAN,SATICOY,"(34.2095, -118.4309)"

In [33]:
start_date = '01/01/2018'
end_date = '12/31/2018'

mask_18 = (arrest_data['Arrest Date'] >= '01/01/2018') & (arrest_data['Arrest Date'] <= '12/31/2018')

In [34]:
arrest_data_18 = arrest_data.loc[mask_18]

In [35]:
arrest_data_18.tail(3)

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
1290588,5509344,2018-12-31,720.0,11,Northeast,1133,25,M,H,6.0,Larceny,M,490.2PC,PETTY THEFT,3100 GLENDALE BL,NaN,"(34.1119, -118.2529)"
1290595,5509947,2018-12-31,2320.0,4,Hollenbeck,408,23,M,H,16.0,Narcotic Drug Laws,F,11378HS,POSSESSION CONTROLLED SUBSTANCE FOR SALE,HUNTINGTON,ROSEMEAD,"(34.0872, -118.176)"
1290614,5509405,2018-12-31,1200.0,19,Mission,1921,28,F,H,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,15100 POLK ST,NaN,"(34.3009, -118.4696)"

In [36]:
feell =  arrest_data_18['Arrest Type Code'].str.contains('F')

felo_18 = arrest_data_18[feell]

In [37]:
felo_18.tail(3)

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
1290583,5509487,2018-12-31,1545.0,1,Central,155,55,M,B,8.0,Other Assaults,F,422(A)PC,TERRORIZE CAUSING FEAR,5TH ST,MAPLE,"(34.0454, -118.2466)"
1290595,5509947,2018-12-31,2320.0,4,Hollenbeck,408,23,M,H,16.0,Narcotic Drug Laws,F,11378HS,POSSESSION CONTROLLED SUBSTANCE FOR SALE,HUNTINGTON,ROSEMEAD,"(34.0872, -118.176)"
1290614,5509405,2018-12-31,1200.0,19,Mission,1921,28,F,H,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,15100 POLK ST,NaN,"(34.3009, -118.4696)"

In [38]:
felo_18.shape

(34948, 17)

In [39]:
felo_18.shape

(34948, 17)

In [40]:
# equation of the line of  best fit : Y = mX + b

# the line of best fits passes through points K(2010, 1), L(2018, 34948),  m = 34948-1/2018-2010 <==> m = 34947/8 = 4368.375

# if X = 2010, Y = 1, B = Y - mX  <==> B = 1 - 4368.37 x 2010 <==> b = - 8,780,432.75

# Equation of the line of best fit Y = 4368.375X - 8,780,432.75

# extrapolation: 

# if X = 2019, Y= 4368.375 X 2019 - 8,780,432.75 = 39,316.375

# So if X = 2019, Y = 39,316 representing the point M(2019, 39,316)

In [41]:
arrest_data_18['Area Name'].value_counts(dropna=False).head()

Central        10951
Hollywood       9715
Rampart         7345
Pacific         6778
77th Street     6259
Name: Area Name, dtype: int64

In [42]:
arrest_data_18['Area Name'].value_counts(dropna=False).tail()

Devonshire    3146
Topanga       3094
Foothill      3006
West LA       2687
Wilshire      2467
Name: Area Name, dtype: int64

In [43]:
emil_2018 = arrest_data_18[~arrest_data_18['Charge Group Description'].isin(["Pre-Delinquency", "Non-Criminal Detention"])]

In [44]:
emil_2018.head(100)

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
156,5213460,2018-01-24,1930.0,6,Hollywood,668,29,M,H,10.0,Fraud/Embezzlement,F,530.5(A)PC,GET CREDIT/ETC OTHER'S ID,ST ANDREWS,FOUNTAIN,"(34.0949, -118.3109)"
157,5257944,2018-03-15,310.0,7,Wilshire,743,33,F,O,1.0,Homicide,F,191.5(B)PC,VEH MANSLAUGHTR/OPER VESSEL DUI & DUR FEL,OLYMPIC,MASSELIN,"(34.0574, -118.3547)"
158,5328813,2018-06-01,1800.0,3,Southwest,356,44,F,B,16.0,Narcotic Drug Laws,F,11379(A)HS,TRANSPORT/SELL CONTROLLED SUBSTANCE,1600 W 36TH PL,NaN,"(34.0219, -118.3061)"
159,5336331,2018-06-10,200.0,13,Newton,1364,23,M,H,12.0,Weapon (carry/poss),F,25400(A)2PC,CARRYING CONCEALED WEAPON UPON PERSON,1200 E 50TH ST,NaN,"(33.998, -118.2543)"
160,5360731,2018-07-07,2330.0,18,Southeast,1832,32,M,B,12.0,Weapon (carry/poss),F,29800(A)1PC,POSS F/ARM BY CONVICTED FELON/ADDICT/ETC,10700 S MAIN ST,NaN,"(33.9392, -118.2739)"
161,5404690,2018-08-25,1850.0,18,Southeast,1832,39,M,B,12.0,Weapon (carry/poss),F,29800(A)1PC,POSS F/ARM BY CONVICTED FELON/ADDICT/ETC,10600 S MAIN ST,NaN,"(33.9402, -118.2739)"
162,5406551,2018-08-27,2300.0,18,Southeast,1842,31,M,B,12.0,Weapon (carry/poss),F,25400(A)1PC,CARRY CONCEALED WEAPON IN VEHICLE,109TH ST,GRAND,"(33.9374, -118.2805)"
165,5419122,2018-09-10,1620.0,12,77th Street,1251,57,M,B,8.0,Other Assaults,F,422(A)PC,TERRORIZE CAUSING FEAR,3100 W 71ST ST,NaN,"(33.9757, -118.3265)"
166,5430543,2018-09-23,1830.0,13,Newton,1321,25,M,H,24.0,Miscellaneous Other Violations,F,594(B)(1)PC,VANDALISM W/LOSS VALUED EQ OR > $400,23RD,TRINITY,"(34.0289, -118.2686)"
167,5449454,2018-10-15,2330.0,1,Central,157,43,M,H,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,SPRING,5TH,"(34.0416, -118.244)"
172,5449463,2018-10-15,2330.0,1,Central,154,32,M,H,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,SPRING ST,6TH,"(34.046, -118.2509)"
173,5452727,2018-10-19,1935.0,1,Central,100,26,M,B,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,8TH ST,LOS ANGELES,"(34.0413, -118.2517)"
174,5456681,2018-10-25,30.0,6,Hollywood,643,48,M,H,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",VINE,HOLLYWOOD,"(34.1007, -118.3494)"
175,5460361,2018-10-29,1550.0,12,77th Street,1208,32,F,H,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,HOOVER,VERNON,"(34.0027, -118.2871)"
176,5464308,2018-11-03,350.0,1,Central,159,27,M,W,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,7TH ST,ALAMEDA,"(34.035, -118.2386)"
177,5471809,2018-11-12,2315.0,1,Central,138,20,M,H,7.0,Vehicle Theft,F,10851(E)VC,TAKE VEH:NO CNSNT:SPEC PR,4TH ST,TOWNE,"(34.0444, -118.2407)"
178,5476070,2018-11-18,300.0,1,Central,185,25,M,B,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,11TH ST,HILL ST,"(34.0402, -118.2598)"
179,5476213,2018-11-18,1000.0,12,77th Street,1204,42,M,H,8.0,Other Assaults,F,422(A)PC,TERRORIZE CAUSING FEAR,1100 W 47TH ST,NaN,"(34.0006, -118.2937)"
180,5477205,2018-11-19,1600.0,13,Newton,1347,19,M,H,12.0,Weapon (carry/poss),F,25850(A)PC,CARRY LOADED F/ARM PRSON/HEH PUBLIC PLACE,45TH,STANTON,"(34.0096, -118.244)"
181,5477482,2018-11-20,705.0,1,Central,134,35,F,W,24.0,Miscellaneous Other Violations,F,594(A)(1)PC,DEFACE PROPERTY,4TH ST,BROADWAY,"(34.0495, -118.2494)"
182,5478144,2018-11-21,811.0,12,77th Street,1208,47,M,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",51ST,FIGUEROA,"(33.9965, -118.2827)"
183,5478957,2018-11-22,940.0,8,West LA,827,21,F,W,22.0,Driving Under Influence,F,23153(A)VC,DUI ALCOHOL CAUSING INJURY,SAN VICENTE,BARRINGTON,"(34.0536, -118.4655)"
184,5482231,2018-11-26,2320.0,20,Olympic,2019,18,M,H,3.0,Robbery,F,211PC,ROBBERY,3400 W 3RD ST,NaN,"(34.0728, -118.2878)"
185,5485057,2018-11-30,840.0,1,Central,155,38,M,H,5.0,Burglary,F,459PC,BURGLARY,6TH ST,WALL ST,"(34.0435, -118.2471)"
186,5485873,2018-12-01,1350.0,20,Olympic,2076,37,M,B,8.0,Other Assaults,M,243(B)PC,BATTERY ON PO/EMERGENCY PERSONNEL W/O INJ,PICO BL,BERENDO ST,"(34.0473, -118.2936)"
187,5488322,2018-12-04,1530.0,20,Olympic,2029,26,M,H,24.0,Miscellaneous Other Violations,F,594(A)(2)PC,DAMAGE PROPERTY,4TH,SHATTO,"(34.067, -118.2899)"
188,5492070,2018-12-09,1847.0,20,Olympic,2039,33,M,W,15.0,Against Family/Child,M,273.6(A)PC,DISOBEY DOMESTIC RELATIONS COURT ORDER,2800 LEEWARD AV,NaN,"(34.0588, -118.2842)"
189,5493854,2018-12-11,2020.0,13,Newton,1363,39,F,H,12.0,Weapon (carry/poss),F,25400(A)1PC,CARRY CONCEALED WEAPON IN VEHICLE,AVALON,51ST ST,"(33.9966, -118.2652)"
190,5497380,2018-12-15,2120.0,7,Wilshire,706,36,M,H,12.0,Weapon (carry/poss),F,29800(A)1PC,POSS F/ARM BY CONVICTED FELON/ADDICT/ETC,MELROSE,HIGHLAND,"(34.0835, -118.3386)"
191,5497391,2018-12-15,2120.0,7,Wilshire,706,27,M,H,12.0,Weapon (carry/poss),M,26100(A)PC,PERMIT ANOTHER BRING LOADED F/ARM IN VEH,MELROSE AV,HIGHLAND AV,"(34.0835, -118.3386)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,5477124,2018-11-19,1245.0,3,Southwest,336,56,M,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",2100 W 28TH ST,NaN,"(34.03, -118.312)"
2623,5482197,2018-11-26,2215.0,16,Foothill,1681,27,M,H,12.0,Weapon (carry/poss),F,29800(A)1PC,POSS F/ARM BY CONVICTED FELON/ADDICT/ETC,8500 CRANFORD AV,NaN,"(34.2253, -118.401)"
2624,5482230,2018-11-27,15.0,5,Harbor,529,38,F,W,5.0,Burglary,F,459PC,BURGLARY,22ND ST,MINER,"(33.7753, -118.2456)"
2625,5482424,2018-11-27,720.0,20,Olympic,2044,25,F,H,7.0,Vehicle Theft,F,10851(E)VC,TAKE VEH:NO CNSNT:SPEC PR,800 S NORMANDIE AV,NaN,"(34.0561, -118.302)"
2626,5482715,2018-11-27,1520.0,20,Olympic,2029,22,F,H,6.0,Larceny,M,459.5PC,SHOPLIFTING,600 S VIRGIL AV,NaN,"(34.0637, -118.287)"
2627,5489624,2018-12-06,815.0,5,Harbor,531,34,F,B,3.0,Robbery,F,A211PC,ATTEMPT - ROBBERY,26000 FRAMPTON AV,NaN,"(33.7866, -118.3044)"
2628,5493924,2018-12-12,315.0,2,Rampart,248,32,M,B,5.0,Burglary,F,459PC,BURGLARY,1200 W 6TH ST,NaN,"(34.0579, -118.2649)"
2629,5484286,2018-11-29,1220.0,18,Southeast,1822,57,M,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",10200 S MAIN ST,NaN,"(33.9438, -118.2739)"
2630,5464231,2018-11-02,1830.0,2,Rampart,257,31,M,H,4.0,Aggravated Assault,F,245(A)(2)PC,ADW W/FIREARM,1400 W 6TH ST,NaN,"(34.0562, -118.2673)"
2631,5424104,2018-09-15,2300.0,18,Southeast,1871,36,M,H,23.0,Moving Traffic Violations,F,20001(A)VC,HIT AND RUN CAUSING INJURY/DEATH,FIGUEROA,ROSECRANS,"(33.9019, -118.2827)"
2632,5495647,2018-12-13,2315.0,2,Rampart,233,16,M,H,24.0,Miscellaneous Other Violations,F,594(A)(2)PC,DAMAGE PROPERTY,3RD ST,RAMPART BL,"(34.0667, -118.2797)"
2633,5500179,2018-12-19,930.0,2,Rampart,249,54,M,W,4.0,Aggravated Assault,F,417.6(A)PC,EXHIBIT/DRAW FIREARM W/GBI,6TH ST,BEAUDRY AV,"(34.0529, -118.2596)"
2634,5506393,2018-12-27,1630.0,16,Foothill,1682,34,M,W,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,11800 REDBANK ST,NaN,"(34.2252, -118.3951)"
2635,5507245,2018-12-28,1540.0,12,77th Street,1259,36,F,B,8.0,Other Assaults,F,422(A)PC,TERRORIZE CAUSING FEAR,7500 AVALON BL,NaN,"(33.9722, -118.2652)"
2636,5509169,2018-12-30,2345.0,18,Southeast,1802,38,M,B,9.0,Forgery/Counterfeit,F,484E(D)PC,ACQUIRE ACCESS CARD IN 4+ NAMES > 12 MOS,88TH ST,MAIN ST,"(33.9572, -118.2739)"
2637,5509684,2018-12-31,2310.0,3,Southwest,397,19,F,H,8.0,Other Assaults,F,422(A)PC,TERRORIZE CAUSING FEAR,BUDLONG,VERNON,"(34.0037, -118.2959)"
2658,5500596,2018-12-20,15.0,18,Southeast,1863,38,M,B,7.0,Vehicle Theft,F,487(D)(1)PC,GRAND THEFT AUTO/HORSE/ETC,AVALON BL,IMPERIAL HY,"(33.9311, -118.2652)"
4733,5195827,2018-01-04,1935.0,13,Newton,1331,21,M,H,3.0,Robbery,F,211PC,ROBBERY,200 E 28TH ST,NaN,"(34.0228, -118.2686)"
4734,5218232,2018-01-29,1955.0,6,Hollywood,646,28,M,B,24.0,Miscellaneous Other Violations,F,3056PC,VIOLATION OF PAROLE:FELONY,CAHUENGA,SELMA,"(34.0998, -118.3295)"
4735,5218250,2018-01-29,1955.0,6,Hollywood,646,24,M,B,11.0,Receive Stolen Property,F,496(A)PC,RECEIVING KNOWN STOLEN PROPERTY >$950,CAHUENGA,SELMA,"(34.0998, -118.3295)"
4736,5219480,2018-01-31,225.0,15,N Hollywood,1503,23,M,H,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",12100 HART ST,NaN,"(34.1976, -118.3965)"
4737,5254796,2018-03-11,1230.0,3,Southwest,307,59,F,B,3.0,Robbery,F,211PC,ROBBERY,2400 CRENSHAW BL,NaN,"(34.0338, -118.337)"
4738,5267062,2018-03-26,345.0,10,West Valley,1007,24,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,8000 LOUISE AV,NaN,"(34.2157, -118.5099)"
4739,5270090,2018-03-29,931.0,8,West LA,836,53,M,W,6.0,Larceny,F,487(A)PC,GRAND THEFT MONEY/PROPERTY > $400,PICO BL,PROSSER ST,"(34.0524, -118.4248)"
4740,5274987,2018-04-04,115.0,6,Hollywood,645,24,M,B,24.0,Miscellaneous Other Violations,F,594(A)(2)PC,DAMAGE PROPERTY,HOLLYWOOD,HIGHLAND,"(34.1016, -118.3387)"
4743,5349417,2018-06-24,2130.0,3,Southwest,362,27,F,B,8.0,Other Assaults,F,243(C)(1)PC,BATTERY ON CUSTODIAL OFFICER/FIREFIGHTER/,3900 COCO AV,NaN,"(34.0155, -118.3497)"
4744,5368563,2018-07-16,1300.0,3,Southwest,361,23,M,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",CHESPEALE,RODEO,"(34.0171, -118.3531)"
4745,5382082,2018-07-31,1700.0,12,77th Street,1241,24,F,H,8.0,Other Assaults,F,243(C)(2)PC,BATTERY ON PEACE OFFICER,6500 VICTORIA AV,NaN,"(33.9806, -118.3323)"
4746,5382151,2018-07-31,1700.0,12,77th Street,1241,34,M,H,8.0,Other Assaults,F,243(C)(1)PC,BATTERY ON CUSTODIAL OFFICER/FIREFIGHTER/,6500 S VICTORIA AV,NaN,"(33.9806, -118.3323)"
4747,5382764,2018-08-01,1200.0,17,Devonshire,1783,21,M,H,24.0,Miscellaneous Other Violations,F,594(A)PC,VANDALISM,9000 VANALDEN AV,NaN,"(34.2341, -118.5493)"

In [45]:
'Pre-Delinquency' in emil_2018['Charge Group Description']

False

In [46]:
"Non-Criminal Detention" in emil_2018['Charge Group Description']

False

In [51]:
import re

regex = re.compile(r"\s([A-Z]....)\s")

booleans = []

for result in emil_2018['Charge Group Description']:
    
    if not re.search('\s([A-Z]....)\s', result):
        
        booleans.append(True)
        
    else:
        
        booleans.append(False)

TypeError: expected string or bytes-like object